version: '3'
services:
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
      - 8081:80
      - 444:443
    volumes:
      - ./pic-sure-auth-ui/src/main/webapp:/usr/local/apache2/htdocs
      - ./pic-sure-auth-ui/target/webjars/META-INF/resources/webjars:/usr/local/apache2/htdocs/admin/webjars
      - ./pic-sure-auth-ui/src/main/resources:/usr/local/apache2/htdocs/admin/settings
    networks:
      - pl-docker-dev_open
      - pl-docker-dev_closed
    environment:
      - PROXY=httpd
      - PROXY_RULE=~ ^/admin/(.*)$$
      - PROXY_PATH=/admin
      - PROXY_PORT=80
      - PROXY_COOKIE=true
  picsureauth:
    build:
      context: pic-sure-auth-services
      dockerfile: Dockerfile
    command: --debug *:8787
    depends_on:
      - picsureauthdb
    environment:
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET:-secret}
      - AUTH_USER_ID_CLAIM = sub
      - AUTH_MYSQLADDRESS=picsureauthdb
      - AUTH0TOKEN=${AUTH0TOKEN}
      - AUTH0HOST=https://avillachlab.auth0.com/api/v2/users
      - PROXY=picsureauth
      - PROXY_RULE=~ ^/picsureauth/(.*)$$
      - PROXY_PATH=/pic-sure-auth-services/auth
      - PROXY_PORT=8080
      - PROXY_COOKIE=true
    ports:
      - 8080
    expose:
      - 8080
    networks:
      - pl-docker-dev_closed

  picsureauthdb:
    image: dbmi/auth-db:5.7.22_initial
    command: --datadir=/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=${AUTH_MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=auth
    restart: always
    expose:
      - 3306
    volumes:
      - picsure-auth-data:/mysql/data
    networks:
      - pl-docker-dev_closed

networks:
  pl-docker-dev_open:
    external:
      name: pl-docker-dev_default
  pl-docker-dev_closed:
    external:
      name: pl-docker-dev_default

volumes:
  picsure-auth-data:
